name:                sparrow
version:             0.0.1.3
git:                 "git://git.localcooking.com/tooling/sparrow.git"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 Local Cooking Inc."
category:            Web
synopsis:            Unified streaming dependency management for web apps

ghc-options: -Wall

extra-source-files:
- README.md

description:         Please see the README on Github at <https://git.localcooking.com/tooling/sparrow#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-attoparsec
- async
- attoparsec
- attoparsec-uri >= 0.0.4
- bytestring
- deepseq
- exceptions
- extractable-singleton
- hashable
- http-client
- http-client-tls
- http-types
- list-t
- monad-control
- monad-control-aligned
- mtl
- nested-routes >= 9.0.0.1
- path
- path-extra >= 0.0.6
- pred-trie >= 0.6.0.1
- stm
- strict
- text
- tmapchan
- tmapmvar >= 0.0.4
- transformers
- unordered-containers
- urlpath >= 8.0.1
- uuid
- wai >= 0.12.4
- wai-middleware-content-type >= 0.6.1.1
- wai-transformers >= 0.1.0
- websockets >= 0.12.4.0
- websockets-simple >= 0.1.2.1
- wuss

library:
  source-dirs: src
