name:                sparrow
version:             0.0.0
git:                 "git://git.localcooking.com/tooling/sparrow.git"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 Local Cooking Inc."
category:            Web
synopsis:            Unified streaming dependency management for web apps

ghc-options: -Wall

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://git.localcooking.com/tooling/sparrow#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-attoparsec
- async
- attoparsec
- attoparsec-uri >= 0.0.4
- bytestring
- deepseq
- exceptions
- extractable-singleton
- hashable
- http-client
- http-client-tls
- http-types
- list-t
- monad-control
- monad-control-aligned
- mtl
- nested-routes >= 9.0.0
- path
- path-extra >= 0.0.6
- pred-trie >= 0.6.0.1
- stm
- strict
- text
- tmapchan
- tmapmvar >= 0.0.4
- transformers
- unordered-containers
- urlpath >= 8.0.1
- uuid
- wai-middleware-content-type >= 0.6.0
- wai-transformers
- websockets >= 0.12.3.1
- websockets-simple >= 0.1.1
- wuss

library:
  source-dirs: src

tests:
  sparrow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - sparrow
